export const getDefaultState = () => {
  return {
    apiUrl: "",
    tab: "map",
    tabBy: "sicks",
    legend: "Fonte: Programa Nacional de Imunização (PNI), disponibilizadas no TabNet-DATASUS",
    form: {
      sickImmunizer: null,
      sicks: [],
      immunizers: [],
      type: null,
      types: [],
      local: [],
      locals: [],
      dose: null,
      doses: [],
      period: null,
      years: null,
      periodStart: null,
      periodEnd: null,
      granularity: null,
      granularities: [],
    },
    yearSlideAnimation: false,
    autoFilters: null,
    aboutVaccines: null,
    mandatoryVaccineYears: null,
    lastUpdateDate: null,
    titles: null,
    genericModal: null,
    genericModalTitle: null,
    genericModalLoading: false,
    extraFilterButton: null,
    genericModalShow: false,
    csvAllDataLink: null,
    doseBlocks: null,
    granularityBlocks: null,
    disableMap: false,
    disableChart: false,
    loading: false
  }
}
